apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: protect-from-sensitive-data
  annotations:
    policies.kyverno.io/title: Ensure variables are used for secrets to protect sensitive data
    policies.kyverno.io/category: OCI Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      Ensure we do not hardcode sensitive data as per https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Sensitive_Data.htm
spec:
  rules:
    - name: validate-no-sensitive-data-hardcode
      match:
        all:
        - ($analyzer.resource.type): terraform-config
      assert:
        all:
        - message: Ensure we do not hardcode sensitive data as per https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Sensitive_Data.htm
          check:
            resource:
              ~.(oci_database_database.values(@)[].database[]):
                admin_password:
                  (contains(@,'var.')): true
                db_name:
                  (contains(@,'var.')): true
