apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: check-cost-center-tagging
  annotations:
    policies.kyverno.io/title: Ensure Cost Center tags are enabled
    policies.kyverno.io/category: OCI Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Ensure Resources are tagged to track resources used for specific purposes, or to aggregate them, report on them, or take bulk actions on them. Reference: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Tagging_Resources.htm
spec:
  rules:
    - name: check-cost-center-tag
      match:
        all:
        - ($analyzer.resource.type): terraform-config
        - (resource.oci_identity_compartment != null): true
      assert:
        all:
        - message: OCI resources must be tagged -- Operations.CostCenter must be defined as per https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Tagging_Resources.htm#tagging_resources
          check:
            ~.resource:
              ~.(values(@)[].defined_tags):
                ("Operations.CostCenter" != null): true
        - message: OCI resources must be tagged -- a Department must be defined as per https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Tagging_Resources.htm#tagging_resources
          check:
            ~.resource:
                ~.(values(@)[].freeform_tags):
                  ("Department" != null): true
