apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: validate-image-domain
  annotations:
    policies.kyverno.io/title: Ensure right Domain name are used
    policies.kyverno.io/category: OCI Best Practices
    policies.kyverno.io/severity: critical
    policies.kyverno.io/description: >-
      Ensure images for instance are pulled from the right domain. https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Availability_Domains.htm
spec:
  rules:
    - name: validate-image-domain
      match:
        all:
        - ($analyzer.resource.type): terraform-config
        - (resource.oci_core_instance != null): true
      context:
      - name: domain
        variable: oci.domain.name.tiaa.com
      assert:
        all:
        - message: Ensure images for instances are pulled from {{$domain}} https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformbestpractices_topic-Availability_Domains.htm
          check:
            ~.(resource.oci_core_instance.values(@)[].source_details.image_id):
                (contains(@, $domain)): true
